"""initial

Revision ID: f51d3d72b1a2
Revises: 
Create Date: 2026-03-14 21:39:27.049825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51d3d72b1a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('employee_count_range', sa.String(length=50), nullable=True),
    sa.Column('estimated_revenue', sa.String(length=100), nullable=True),
    sa.Column('hq_location', sa.String(length=255), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('funding_stage', sa.String(length=100), nullable=True),
    sa.Column('last_funding_amount', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_franchisor', sa.Boolean(), nullable=False),
    sa.Column('franchise_brand', sa.String(length=255), nullable=True),
    sa.Column('franchise_count', sa.Integer(), nullable=True),
    sa.Column('franchise_fee_range', sa.String(length=100), nullable=True),
    sa.Column('franchise_territories', sa.JSON(), nullable=True),
    sa.Column('franchise_network_id', sa.UUID(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('crm_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_network_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_companies_crm_id'), 'companies', ['crm_id'], unique=False)
    op.create_index(op.f('ix_companies_franchise_brand'), 'companies', ['franchise_brand'], unique=False)
    op.create_index(op.f('ix_companies_is_franchisor'), 'companies', ['is_franchisor'], unique=False)
    op.create_table('icps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('target_industries', sa.JSON(), nullable=True),
    sa.Column('min_employee_count', sa.Integer(), nullable=True),
    sa.Column('max_employee_count', sa.Integer(), nullable=True),
    sa.Column('min_revenue', sa.String(length=100), nullable=True),
    sa.Column('max_revenue', sa.String(length=100), nullable=True),
    sa.Column('target_titles', sa.JSON(), nullable=True),
    sa.Column('target_seniority', sa.JSON(), nullable=True),
    sa.Column('target_geography', sa.JSON(), nullable=True),
    sa.Column('required_tech_stack', sa.JSON(), nullable=True),
    sa.Column('scoring_weights', sa.JSON(), nullable=True),
    sa.Column('custom_criteria', sa.JSON(), nullable=True),
    sa.Column('target_franchise_brands', sa.JSON(), nullable=True),
    sa.Column('min_franchise_count', sa.Integer(), nullable=True),
    sa.Column('max_franchise_count', sa.Integer(), nullable=True),
    sa.Column('is_franchisor_target', sa.Boolean(), nullable=False),
    sa.Column('is_franchisee_target', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crew_run_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='agentrunstatus'), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('icp_id', sa.UUID(), nullable=True),
    sa.Column('leads_sourced', sa.Integer(), nullable=False),
    sa.Column('leads_qualified', sa.Integer(), nullable=False),
    sa.Column('leads_routed', sa.Integer(), nullable=False),
    sa.Column('appointments_set', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['icp_id'], ['icps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('seniority_level', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('icp_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'QUALIFIED', 'DISQUALIFIED', 'ROUTED', 'CONTACTED', 'MEETING_BOOKED', 'CONVERTED', name='leadstatus'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('tier', sa.Enum('HOT', 'WARM', 'COLD', name='leadtier'), nullable=True),
    sa.Column('qualification_reasoning', sa.Text(), nullable=True),
    sa.Column('buying_signals', sa.JSON(), nullable=True),
    sa.Column('assigned_team', sa.String(length=255), nullable=True),
    sa.Column('assigned_rep_id', sa.String(length=255), nullable=True),
    sa.Column('assigned_rep_name', sa.String(length=255), nullable=True),
    sa.Column('routing_reasoning', sa.Text(), nullable=True),
    sa.Column('disqualification_reason', sa.Text(), nullable=True),
    sa.Column('franchise_brand', sa.String(length=255), nullable=True),
    sa.Column('franchise_network_id', sa.UUID(), nullable=True),
    sa.Column('is_network_expansion', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['franchise_network_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['icp_id'], ['icps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('meeting_type', sa.String(length=100), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'), nullable=False),
    sa.Column('rep_email', sa.String(length=500), nullable=False),
    sa.Column('prospect_email', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'LINKEDIN', name='outreachchannel'), nullable=False),
    sa.Column('sequence_step', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'DELIVERED', 'OPENED', 'REPLIED', 'BOUNCED', name='outreachstatus'), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outreach')
    op.drop_table('appointments')
    op.drop_table('leads')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('agent_runs')
    op.drop_table('routing_rules')
    op.drop_table('icps')
    op.drop_index(op.f('ix_companies_is_franchisor'), table_name='companies')
    op.drop_index(op.f('ix_companies_franchise_brand'), table_name='companies')
    op.drop_index(op.f('ix_companies_crm_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
